[package]
name = "sandra-be"
version = "0.0.1"
edition = "2021"

[dependencies]
derivative = "2.2.0"
onvif = { git = "https://github.com/jwolfgram/onvif-rs", branch = "fix-reolink-header-event" }
chrono = "0.4.19"
tokio = { version = "1.0.1", features = ["full"] }
tokio-stream = "0.1"
xml-rs = "=0.8.3"
xmltree = "0.10.2"
xsd-macro-utils = { git = "https://github.com/lumeohq/xsd-parser-rs", rev = "7f3d433" }
xsd-types = { git = "https://github.com/lumeohq/xsd-parser-rs", rev = "7f3d433" }
schema = { git = "https://github.com/jwolfgram/onvif-rs", branch = "fix-reolink-header-event", default-features = false, features = ["analytics", "devicemgmt", "event", "media", "ptz"] }
b_2 = {git = "https://github.com/jwolfgram/onvif-rs", branch = "fix-reolink-header-event" }
url = "2.5.2"
